In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# 1. Load and Prepare Dataset
file_path = '/content/Beds-publication-Timeseries-March-2020-November-2024 (2) (1) (1) (1) (3).xlsx'
census_data = pd.read_excel(file_path, sheet_name='Timeseries type 1 acute trusts', skiprows=12)

# Rename columns
census_data.columns = [
    "Index", "Month", "G&A beds available", "G&A core beds available",
    "G&A escalation beds available", "G&A covid void beds", "G&A beds occupied",
    "G&A occupancy rate", "G&A occupancy rate adjusted for covid void beds",
    "Adult G&A beds available", "Adult core beds available",
    "Adult escalation beds available", "Adult G&A covid void beds",
    "Adult G&A beds occupied", "Adult G&A occupancy rate",
    "Adult G&A occupancy rate adjusted for covid void beds",
    "Paediatric G&A beds available", "Paediatric core beds available",
    "Paediatric escalation beds available", "Paediatric G&A covid void beds",
    "Paediatric G&A beds occupied", "Paediatric G&A occupancy rate",
    "Paediatric G&A occupancy rate adjusted for covid void beds",
    "Adult critical care beds available", "Adult critical care beds occupied",
    "Adult critical care occupancy rate", "Paediatric intensive care beds available",
    "Paediatric intensive care beds occupied", "Paediatric intensive care occupancy rate",
    "Neonatal intensive care beds available", "Neonatal intensive care beds occupied",
    "Neonatal intensive care occupancy rate", "Placeholder",
    "7 or more days", "14 or more days", "21 or more days",
    "7 or more days.1", "14 or more days.1", "21 or more days.1"
]

In [3]:
# Define the columns to select
selected_columns = [
    "Index", "Month", "G&A beds available", "G&A core beds available",
    "G&A escalation beds available", "G&A beds occupied",
    "7 or more days", "14 or more days", "21 or more days",
    "7 or more days.1", "14 or more days.1", "21 or more days.1","G&A occupancy rate"
]

# Create a new DataFrame with only the selected columns
new_census_data = census_data[selected_columns]
new_census_data.drop(columns=['Index'], inplace=True)

new_census_data.to_csv('preprocessed_data.csv', index=False)
new_census_data

<ipython-input-3-310feae488a7>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_census_data.drop(columns=['Index'], inplace=True)

,Month,G&A beds available,G&A core beds available,G&A escalation beds available,G&A beds occupied,7 or more days,14 or more days,21 or more days,7 or more days.1,14 or more days.1,21 or more days.1,G&A occupancy rate
0,March 2020,95804.903226,NaN,NaN,78667.258065,37907.0,22716.0,14753.0,0.481865,0.288761,0.187537,0.821119
1,April 2020,90553.900000,NaN,NaN,52997.700000,21177.0,11035.0,6695.0,0.399583,0.208217,0.126326,0.585261
2,May 2020,89384.677419,NaN,NaN,58407.677419,23145.0,11786.0,6836.0,0.396266,0.201789,0.117039,0.653442
3,June 2020,88952.000000,NaN,NaN,64589.000000,25788.0,13314.0,7767.0,0.399263,0.206134,0.120253,0.726111
4,July 2020,89690.000000,NaN,NaN,68197.000000,27453.0,13981.0,8055.0,0.402554,0.205009,0.118114,0.760363
5,August 2020,89827.000000,NaN,NaN,72610.000000,30118.0,15600.0,8974.0,0.414791,0.214846,0.123592,0.808332
6,September 2020,90233.000000,NaN,NaN,76541.000000,33294.0,17567.0,10333.0,0.434983,0.229511,0.135000,0.848260
7,October 2020,91002.000000,NaN,NaN,77889.000000,34173.0,18159.0,10750.0,0.438740,0.233139,0.138017,0.855904
8,November 2020,88917.000000,NaN,NaN,77696.000000,34718.0,18814.0,11270.0,0.446844,0.242149,0.145053,0.873804
9,December 2020,89140.000000,NaN,NaN,77515.000000,35552.0,19223.0,11415.0,0.458647,0.247991,0.147262,0.869587
10,January 2021,90629.000000,NaN,NaN,79288.000000,36864.0,19734.0,11780.0,0.464938,0.248890,0.148572,0.874863
11,February 2021,89857.000000,NaN,NaN,76713.000000,35662.0,19265.0,11522.0,0.464876,0.251131,0.150196,0.853723
12,March 2021,89625.000000,NaN,NaN,76215.000000,33705.0,18234.0,11106.0,0.442236,0.239244,0.145719,0.850377
13,April 2021,90293.000000,NaN,NaN,78011.000000,33618.0,17923.0,10853.0,0.430939,0.229750,0.139121,0.863976
14,May 2021,91343.000000,NaN,NaN,80578.000000,34121.0,17908.0,10641.0,0.423453,0.222244,0.132058,0.882148
15,June 2021,91778.000000,NaN,NaN,81870.000000,35398.0,18759.0,11189.0,0.432368,0.229132,0.136668,0.892044
16,July 2021,92357.000000,NaN,NaN,82691.000000,36284.0,19366.0,11620.0,0.438790,0.234197,0.140523,0.895341
17,August 2021,92444.000000,NaN,NaN,83310.000000,38048.0,20909.0,12728.0,0.456704,0.250978,0.152779,0.901194
18,September 2021,93150.000000,NaN,NaN,84898.000000,39826.0,22512.0,14023.0,0.469104,0.265165,0.165175,0.911412
19,October 2021,93619.000000,NaN,NaN,86344.000000,40099.0,22441.0,13949.0,0.464410,0.259902,0.161551,0.922291
20,November 2021,94386.000000,NaN,NaN,87566.000000,41227.0,23405.0,14666.0,0.470811,0.267284,0.167485,0.927744
21,December 2021,94390.000000,NaN,NaN,85598.000000,41410.0,23711.0,14935.0,0.483773,0.277004,0.174478,0.906855
22,January 2022,94841.000000,NaN,NaN,87084.000000,44251.0,26454.0,17270.0,0.508142,0.303776,0.198314,0.918210
23,February 2022,95890.000000,NaN,NaN,88753.000000,44128.0,26056.0,16954.0,0.497200,0.293579,0.191025,0.925571
24,March 2022,95945.000000,NaN,NaN,88868.000000,44633.0,26472.0,17155.0,0.502239,0.297880,0.193039,0.926239
25,April 2022,96625.000000,NaN,NaN,89440.000000,46229.0,27860.0,18078.0,0.516872,0.311494,0.202124,0.925640
26,May 2022,96692.000000,NaN,NaN,89749.000000,45245.0,27054.0,17835.0,0.504128,0.301441,0.198721,0.928195
27,June 2022,96370.000000,NaN,NaN,89656.000000,45381.0,27007.0,17670.0,0.506168,0.301229,0.197087,0.930331
28,July 2022,96375.000000,NaN,NaN,89733.000000,45610.0,27335.0,17846.0,0.508286,0.304626,0.198879,0.931082
29,August 2022,96425.000000,NaN,NaN,89509.000000,46458.0,28357.0,18846.0,0.519032,0.316806,0.210549,0.928276
30,September 2022,96668.000000,NaN,NaN,90490.000000,47466.0,29298.0,19824.0,0.524544,0.323771,0.219074,0.936091
31,October 2022,97287.000000,NaN,NaN,91753.000000,48420.0,29533.0,19715.0,0.527721,0.321875,0.214870,0.943117
32,November 2022,97208.000000,NaN,NaN,91792.000000,46983.0,28467.0,18965.0,0.511842,0.310125,0.206608,0.944284
33,December 2022,98217.000000,NaN,NaN,92520.000000,47628.0,28195.0,18417.0,0.514786,0.304745,0.199060,0.941996
34,January 2023,100046.000000,NaN,NaN,94372.000000,49956.0,30095.0,19500.0,0.529352,0.318898,0.206629,0.943286
35,February 2023,99388.000000,NaN,NaN,93711.000000,48397.0,29027.0,19028.0,0.516450,0.309750,0.203050,0.942880
36,March 2023,99223.000000,NaN,NaN,93383.000000,48137.0,28919.0,18972.0,0.515479,0.309682,0.203163,0.941143
37,April 2023,98431.000000,NaN,NaN,91098.000000,46665.0,28257.0,18840.0,0.512251,0.310182,0.206810,0.925501
38,May 2023,98404.000000,NaN,NaN,91699.000000,46379.0,27757.0,18274.0,0.505774,0.302697,0.199282,0.931863
39,June 2023,98205.000000,NaN,NaN,91298.000000,45132.0,26603.0,17294.0,0.494337,0.291386,0.189424,0.929668
40,July 2023,97337.000000,NaN,NaN,89361.000000,43789.0,25879.0,16852.0,0.490024,0.289601,0.188583,0.918058
41,August 2023,97265.000000,95037.0,2224.0,89365.000000,44593.0,26110.0,16988.0,0.498998,0.292173,0.190097,0.918779
42,September 2023,97332.000000,95171.0,2161.0,90578.000000,45328.0,27016.0,17685.0,0.500431,0.298262,0.195246,0.931000
43,October 2023,97371.000000,95086.0,2285.0,91634.000000,45893.0,27096.0,17675.0,0.500829,0.295698,0.192887,0.941000
44,November 2023,98844.000000,96238.0,2606.0,93686.000000,46610.0,27470.0,17826.0,0.497513,0.293214,0.190274,0.948000
45,December 2023,99191.000000,96419.0,2771.0,92262.000000,46035.0,26942.0,17367.0,0.498959,0.292016,0.188236,0.930000
46,January 2024,101384.000000,97799.0,3585.0,95544.000000,48888.0,28987.0,18884.0,0.511680,0.303389,0.197647,0.942000
47,February 2024,101642.000000,98151.0,3491.0,95776.000000,48796.0,29053.0,18896.0,0.509480,0.303343,0.197294,0.942000
48,March 2024,101183.000000,97975.0,3208.0,95084.000000,47740.0,28324.0,18531.0,0.502082,0.297884,0.194891,0.940000
49,April 2024,100902.000000,97968.0,2934.0,94582.000000,48187.0,29010.0,19269.0,0.509473,0.306718,0.203728,0.937000
50,May 2024,100244.000000,97563.0,2681.0,93578.000000,46996.0,27848.0,18274.0,0.502212,0.297591,0.195281,0.934000
51,June 2024,99604.000000,97206.0,2398.0,92654.000000,46081.0,27342.0,17952.0,0.497345,0.295098,0.193753,0.930000
52,July 2024,99170.000000,96959.0,2210.0,91807.000000,45630.0,26951.0,17573.0,0.497021,0.293561,0.191412,0.926000
53,August 2024,98776.000000,96860.0,1917.0,90479.000000,45249.0,26721.0,17453.0,0.500105,0.295328,0.192896,0.916000
54,September 2024,98948.000000,96770.0,2178.0,92129.000000,46142.0,27382.0,17986.0,0.500841,0.297214,0.195226,0.931000
55,October 2024,99602.000000,97053.0,2549.0,93572.000000,46886.0,27471.0,17808.0,0.501069,0.293581,0.190313,0.939000
56,November 2024,100149.000000,97641.0,2507.0,94219.000000,46695.0,27412.0,17908.0,0.495601,0.290939,0.190068,0.941000
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,Note: Adult and paediatric G&A spilt was not c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN